name: pyloncoin
version: master 
summary: Distributed content ledger. The blockchain of media content.
description: |
    Decentralized platform for the registration and distribution of content than certifies the authorship and license of any work o creation making them idelible. Pylonnetwork is the platform that directly empowers artists and creators, offering them an ecosystem where only they are owners to choose the way they distribute their contents.

grade: devel 
confinement: strict 

apps:
  pyloncoin:
     command: desktop-launch pyloncoin-qt
     plugs: [network, home, unity7, network-bind]

parts:
  pyloncoin:
    plugin: autotools
    source: . 
    build-packages:
       - build-essential
       - libtool 
       - autotools-dev
       - automake
       - pkg-config
       - libssl-dev
       - libevent-dev
       - bsdmainutils
       - libboost-system-dev
       - libboost-filesystem-dev
       - libboost-chrono-dev
       - libboost-program-options-dev
       - libboost-test-dev
       - libboost-thread-dev
       - libqt5gui5
       - libqt5core5a
       - libqt5dbus5
       - qttools5-dev
       - qttools5-dev-tools
       - libprotobuf-dev
       - protobuf-compiler     
    after:
       - berkeleydb
       - desktop-qt5

  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
    plugin: nil
    build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
    install: |
      cd build_unix
      make install
    prime:
         - -*      

  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all 
